version: '3.1'

services:
  api:
    volumes:
      - /home/jesuslara/proyectos/navigator//navapi:/home/troc/code
    restart: 'no'
    build:
      context: /home/jesuslara/proyectos/navigator//navapi
      dockerfile: ./Dockerfile
    command: python /home/troc/code/run.py
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - redis
      - rethinkdb
      - memcached
    extra_hosts:
      - nav-api.dev.local:192.168.1.131
      - navigator-dev.dev.local:192.168.1.131
      - rethink.dev.local:192.168.1.131
      - postgres.dev.local:192.168.1.131
    networks:
      infranet:
        aliases:
          - 'api'
  influxdb:
    container_name: influxdb
    image: influxdb
    restart: 'no'
    volumes:
      - /home/jesuslara/docker/volumes/influxdb:/data
    environment:
      - INFLUXDB_GRAPHITE_ENABLED=true
      - INFLUXDB_DB=navigator_dev
      - INFLUXDB_ADMIN_USER=troc_pgdata
      - INFLUXDB_ADMIN_PASSWORD=12345678
      - INFLUXDB_USER=influxdata
      - INFLUXDB_USER_PASSWORD=12345678
    ports:
      - '8086:8086'
      - '2003:2003'
  memcached:
    container_name: memcached
    image: memcached
    restart: 'no'
    command:
      - '-m 256'
    ports:
      - '11211:11211'
  rethinkdb:
    image: rethinkdb
    restart: 'no'
    ports:
      - 8080:8080
      - 28015:28015
      - 29015:29015
    volumes:
      - /home/jesuslara/docker/volumes/rethink:/data
      - /home/jesuslara/proyectos/navigator//backup:/opt
    networks:
      infranet:
        aliases:
          - 'dwh'
  redis:
    image: redis
    restart: 'no'
    ports:
      - 6379:6379
    networks:
      infranet:
        aliases:
          - 'redis'
  postgres:
    image: postgres:11-alpine
    build: ./postgres
    restart: 'no'
    command: postgres -c logging_collector=on -c log_destination=stderr -c log_directory=/logs
    ports:
      - '5432:5432'
    volumes:
      - /home/jesuslara/docker/postgres:/var/lib/postgresql/data
      - /home/jesuslara/proyectos/navigator//backup:/opt
      - /home/jesuslara/docker/logs/postgres:/logs
    environment:
      - PG_DB_USER=troc_pgdata
      - PG_DB_SPUSER=troc_pgdata
      - PG_DB_PASSWORD=12345678
      - PG_DB_DATABASE=navigator_dev
      - POSTGRES_PASSWORD=12345678
    networks:
      infranet:
        aliases:
          - 'postgres'
  mysql:
    image: mysql
    restart: 'no'
    environment:
      - MYSQL_DATABASE=navigator_dev
      - MYSQL_USER=troc_pgdata
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /home/jesuslara/docker/volumes/mysql:/var/lib/mysql
  cassandra:
    image: cassandra
    restart: 'no'
    environment:
      - CASSANDRA_CLUSTER_NAME=navigator
    ports:
      - '7000:7000'
    expose:
      - '7000'
    volumes:
      - /home/jesuslara/docker/volumes/cassandra:/data
networks:
  infranet:
